### ISSUE TITLE
GP bug of DISTINCT and GROUP BY

### ISSUE THREAD

**Issue by zhangce** [dennybritz/deepdive#115]
It turns out GP has the weird bug?

GOOD ONE:
        INSERT INTO dd_graph_weights(initial_value, is_fixed, description)
        SELECT 0.0 as a, false as b, 'fac_relations4-' ||  "features"::text  ||  "relations_formationlocation_is_correct_cardinality"  as c
        FROM fac_relations4_query GROUP BY a, b, c ;

BUGGY ONE:
        INSERT INTO dd_graph_weights(initial_value, is_fixed, description)
        SELECT DISTINCT 0.0, false, 'fac_relations4-' ||  "features"::text  ||  "relations_formationlocation_is_correct_cardinality"
        FROM fac_relations4_query  ;

@dennybritz Can we change all DISTINCT in the system to this weird GROUP BY?

**Comment by dennybritz** [comment]
Done in https://github.com/dennybritz/deepdive/commit/89d13910f82739f8d28e1ac036944178df2cc497
