### ISSUE TITLE
IMPORTANT: sampler's output is not in log?

### ISSUE THREAD

**Issue by zhangce** [dennybritz/deepdive#35]
10:04:11.892 [default-dispatcher-8][profiler][Profiler] DEBUG starting report_id=calibration
10:04:11.893 [default-dispatcher-3][inferenceManager][InferenceManager$PostgresInferenceManager] INFO  writing calibration data
10:04:11.896 [default-dispatcher-8][$a][CalibrationDataWriter] INFO  starting
10:04:11.948 [default-dispatcher-3][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore] INFO  created bucketed_inference_view=relations_formationtemporal_is_correct_inference_bucketed
10:04:11.968 [default-dispatcher-3][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore] INFO  created calibration_view=relations_formationtemporal_is_correct_calibration
10:04:15.765 [default-dispatcher-8][$a][CalibrationDataWriter] INFO  Wrote calibration_file=/lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal.is_correct.tsv
10:04:15.770 [default-dispatcher-8][$a][CalibrationDataWriter] INFO  Running '/lfs/madmax3/0/czhang/deepdive/util/calibration.py /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal.is_correct.tsv /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal.is_correct.png' to generate the calibration plot.
10:04:15.793 [default-dispatcher-3][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore] INFO  created bucketed_inference_view=relations_formationtemporal_global_is_correct_inference_bucketed
10:04:15.813 [default-dispatcher-3][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore] INFO  created calibration_view=relations_formationtemporal_global_is_correct_calibration
10:04:15.932 [default-dispatcher-8][$a][CalibrationDataWriter] WARN  ERROR generating calibration data plot. Run '/lfs/madmax3/0/czhang/deepdive/util/calibration.py /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal.is_correct.tsv /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal.is_correct.png' manually.
10:04:18.129 [default-dispatcher-6][$a][CalibrationDataWriter] INFO  Wrote calibration_file=/lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal_global.is_correct.tsv
10:04:18.130 [default-dispatcher-6][$a][CalibrationDataWriter] INFO  Running '/lfs/madmax3/0/czhang/deepdive/util/calibration.py /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal_global.is_correct.tsv /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal_global.is_correct.png' to generate the calibration plot.
10:04:18.149 [default-dispatcher-3][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore] INFO  created bucketed_inference_view=constants_is_correct_inference_bucketed
10:04:18.169 [default-dispatcher-3][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore] INFO  created calibration_view=constants_is_correct_calibration
10:04:18.279 [default-dispatcher-6][$a][CalibrationDataWriter] WARN  ERROR generating calibration data plot. Run '/lfs/madmax3/0/czhang/deepdive/util/calibration.py /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal_global.is_correct.tsv /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal_global.is_correct.png' manually.

**Comment by dennybritz** [comment]
There must be something else wrong in your `application.conf` file.

On Fri, Jan 24, 2014 at 1:32 PM, zhangce notifications@github.com wrote:

> 10:04:11.892 [default-dispatcher-8][profiler][Profiler] DEBUG starting
> report_id=calibration
> 10:04:11.893
> [default-dispatcher-3][inferenceManager][InferenceManager$PostgresInferenceManager]
> INFO writing calibration data
> 10:04:11.896 [default-dispatcher-8][$a][CalibrationDataWriter] INFO
> starting
> 10:04:11.948
> [default-dispatcher-3][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore]
> INFO created
> bucketed_inference_view=relations_formationtemporal_is_correct_inference_bucketed
> 10:04:11.968
> [default-dispatcher-3][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore]
> INFO created
> calibration_view=relations_formationtemporal_is_correct_calibration
> 10:04:15.765 [default-dispatcher-8][$a][CalibrationDataWriter] INFO Wrote
> calibration_file=/lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal.is_correct.tsv
> 10:04:15.770 [default-dispatcher-8][$a][CalibrationDataWriter] INFO
> Running '/lfs/madmax3/0/czhang/deepdive/util/calibration.py
> /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal.is_correct.tsv
> /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal.is_correct.png'
> to generate the calibration plot.
> 10:04:15.793
> [default-dispatcher-3][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore]
> INFO created
> bucketed_inference_view=relations_formationtemporal_global_is_correct_inference_bucketed
> 10:04:15.813
> [default-dispatcher-3][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore]
> INFO created
> calibration_view=relations_formationtemporal_global_is_correct_calibration
> 10:04:15.932 [default-dispatcher-8][$a][CalibrationDataWriter] WARN ERROR
> generating calibration data plot. Run
> '/lfs/madmax3/0/czhang/deepdive/util/calibration.py
> /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal.is_correct.tsv
> /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal.is_correct.png'
> manually.
> 10:04:18.129 [default-dispatcher-6][$a][CalibrationDataWriter] INFO Wrote
> calibration_file=/lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal_global.is_correct.tsv
> 10:04:18.130 [default-dispatcher-6][$a][CalibrationDataWriter] INFO
> Running '/lfs/madmax3/0/czhang/deepdive/util/calibration.py
> /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal_global.is_correct.tsv
> /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal_global.is_correct.png'
> to generate the calibration plot.
> 10:04:18.149
> [default-dispatcher-3][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore]
> INFO created bucketed_inference_view=constants_is_correct_inference_bucketed
> 10:04:18.169
> [default-dispatcher-3][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)][PostgresInferenceDataStoreComponent$PostgresInferenceDataStore]
> INFO created calibration_view=constants_is_correct_calibration
> 10:04:18.279 [default-dispatcher-6][$a][CalibrationDataWriter] WARN ERROR
> generating calibration data plot. Run
> '/lfs/madmax3/0/czhang/deepdive/util/calibration.py
> /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal_global.is_correct.tsv
> /lfs/madmax3/0/czhang/deepdive/target/calibration/relations_formationtemporal_global.is_correct.png'
> manually.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dennybritz/deepdive/issues/35
> .

## 

Best,
Denny

**Comment by dennybritz** [comment]
@zhangce Fixed. Unfortunately for now this does a double logging as so:

```
16:58:29.170 [Thread-8][akka://SamplerSpec/user/$$a][Sampler] INFO  16:58:29.169 [main] DEBUG org.dennybritz.sampler.Sampler - iteration=9/10
```

It's a bit of work to combine the logging because we are calling the jar directly, so I guess we need to live with that for now.
