### ISSUE TITLE
Something weird

### ISSUE THREAD

**Issue by zhangce** [dennybritz/deepdive#37]
Some weird observation...

I ran two versions, one on Mac and one on madmax... Seems that some key of the input of an extractor (got by json.loads) does not have the same key for these two versions?

Query is

```
#freq_features:{
#    output_relation: "top_features"
#    input: "SELECT feature, count(*) AS ct FROM relation_features GROUP by feature ORDER BY ct DESC"
#    udf: "../kbp/udf/freq_features.py"
#    output_batch_size: 100000
#    dependencies: ["load_relation_features"]
#}
```

Ce

**Comment by dennybritz** [comment]
Hm, that sounds strange.. Can you be more specific in what keys you are actually getting?
