### ISSUE TITLE
Do we need a Q&A section?

### ISSUE THREAD

**Issue by zhangce** [dennybritz/deepdive#42]
For example:

Q: When I use Greeplum, I see the error "ERROR: data line too long. likely due to invalid csv data". But my program runs fine using PostgreSQL.

A: Tune gp_max_csv_line_length in Greenplum.

This kind of things might be confusing to the user, and they really took time to discover and get workaround although extremely simple...

**Comment by dennybritz** [comment]
Added FAQ to the Greenplum page
