### ISSUE TITLE
Smoker's Example

### ISSUE THREAD

**Issue by dennybritz** [dennybritz/deepdive#5]
Translate the Smokers Example from http://homes.cs.washington.edu/~pedrod/kbmn.pdf to DeepDive.

**Comment by zifeishan** [comment]
Problem with smoker's example:

```
deepdive.inference.factors: {
  smokesFactor.input_query: "SELECT people.* FROM people"
  smokesFactor.function: "people.has_cancer = Imply(people.smokes)"
  smokesFactor.weight: "?(people.gender)"

  # More factors...
}
```

If an evidence says that people.smokes is false, it will increase the weight of smokesFactor. 
Should input_query be "SELECT people.\* FROM people where people.smokes = true"?

**Comment by zhangce** [comment]
@zifeishan Great questions! Lets put it in FAQ
