### ISSUE TITLE
Gnuplot issue

### ISSUE THREAD

**Issue by zifeishan** [dennybritz/deepdive#63]
On my mac when I'm running examples, at the last step:

15:02:09.462 [default-dispatcher-4][profiler][Profiler] INFO  ERROR generating calibration data plot. Run 'List(gnuplot, -e, input_file='/Users/Robin/Documents/repos/research/deepdive/target/calibration/has_spouse.is_true.tsv';output_file='/Users/Robin/Documents/repos/research/deepdive/target/calibration/has_spouse.is_true.png', /Users/Robin/Documents/repos/research/deepdive/util/calibration.plg)' manually. [0 ms]

I have gnuplot_py installed.

**Comment by zifeishan** [comment]
Update error log:

```
set term png size 1200,300
         ^
"/Users/Robin/Documents/repos/research/deepdive/util/calibration.plg", line 3: unknown or ambiguous terminal type; type just 'set terminal' for a list
```

No png installed in my gnuplot.

**Comment by dennybritz** [comment]
http://stackoverflow.com/questions/10496469/how-do-i-enable-the-pngcairo-terminal-in-gnuplot
