### ISSUE TITLE
Add in FAQ

### ISSUE THREAD

**Issue by zhangce** [dennybritz/deepdive#66]
F: Can I have a dictionary with precise terms (e.g., Cretaceous), and less-precise terms (e.g., Recent, Word)?

A: We suggest that you separate them into two dictionaries. The reason is that in that way DeepDive will learn the weight for each dictionary and choose the one to trust.

**Comment by dennybritz** [comment]
@zhangce  Thanks! Not sure if I completely understand. Do you mean you have a feature for "in_dictionary" for each of those?

**Comment by dennybritz** [comment]
Added.
