### ISSUE TITLE
How to debug extractors?

### ISSUE THREAD

**Issue by zifeishan** [dennybritz/deepdive#70]
@dennybritz I want to print some error messages to help debugging in the extractors, but I cannot print to stdout since it will be streamed by our system. 

Is there an easy way for developers to do the debug printing? If so, maybe the Q&A / walkthrough should mention it...

**Comment by dennybritz** [comment]
Good point, we forgot to add that. You can print to stderr (`sys.stderr.write` in Python), and it will appear in the log files. I'll add it to the FAQ and walkthrough.
