### ISSUE TITLE
ERROR of spouse relation

### ISSUE THREAD

**Issue by zhangce** [dennybritz/deepdive#99]
10:49:17.525 [default-dispatcher-6][taskManager][TaskManager] INFO  Tasks not_eligible: Set(shutdown, inference, report, calibration)
10:49:17.566 [][][StatementExecutor$$anon$1] ERROR SQL execution failed (Reason: ERROR: function concat_ws(unknown, unknown, text) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 143):

   CREATE TABLE dd_f_has_spouse_features_query AS (SELECT row_number() OVER() - 1 as factor_id, dd_f_has_spouse_features_query_tmp.*, concat_ws(',','f_has_spouse_features', "feature" ) AS dd_weight FROM dd_f_has_spouse_features_query_tmp) WITH DATA

10:49:17.569 [default-dispatcher-3][profiler][Profiler] DEBUG ending report_id=f_has_spouse_features
10:49:17.570 [default-dispatcher-2][taskManager][TaskManager] INFO  Completed task_id=f_has_spouse_features with Failure(org.postgresql.util.PSQLException: ERROR: function concat_ws(unknown, unknown, text) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 143)
10:49:17.579 [default-dispatcher-2][taskManager][TaskManager] ERROR task=f_has_spouse_features Failed: org.postgresql.util.PSQLException: ERROR: function concat_ws(unknown, unknown, text) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 143

**Comment by zhangce** [comment]
Need > Postgres 9.1...

Can we add this to documentation?

**Comment by zifeishan** [comment]
I encountered this problem too.. 

On Mar 9, 2014, at 10:58 AM, zhangce notifications@github.com wrote:

> Need > Postgres 9.1...
> 
> Can we add this to documentation?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Zifei Shan
M.S. student in Computer Science, Stanford University (2015)
B.S. in Computer Science, Peking University (2013)
